{
    "name": "Build template",
    "on": ["pull_request", "push", "workflow_dispatch"],
    "jobs": {
        "build": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {"uses": "actions/checkout@v2"},
                {"uses": "cachix/install-nix-action@v16"},
                {"run": "nix run > template.json"},
                {"uses": "actions/upload-artifact@v2", "with": {"name": "template.json", "path": "template.json"}}
            ]
        }
    }
}
